default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %> || 'adskajhsdlfkjahsdkahsdklghasldkghalhsk'

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
